### ISSUE TITLE
Doorbell G4 Ring stops working Firmware 4.68.16

### ISSUE THREAD

**Issue by SchmidSP** [seaside1/unifiprotect#17] opened 2023-12-01 16:25 UTC
Early Access Firmware 4.68.16
Cloudkey Gen2* V 3.2.7
Protect V 2.10.10
No ring anymore
Last ring message still ok.
Only no signal on Doorbell
Openhab 4.0.3
with unifiprotect-4.0.0-v1.2
If you need any Protocols just ask.

**Comment by SchmidSP** [comment] 2023-12-04 15:11
Tested same behavior on Protect 2.9.42 offical.

**Comment by seaside1** [comment] 2023-12-04 18:57
Not sure how to handle this. I have updated to:
UniFi OS: v3.2.7
Protect:  2.10.10

I get motion and ring events. However intermittently Ring is not working.
I can't always reproduce this, if you can reproduce, could enable debug logging,  and pm your bootstrap.json and the logs (espcially the frames containing ring notification).
Edit: Last 10 ring notifications worked on my doorbell.

**Comment by SchmidSP** [comment] 2023-12-05 10:46
Send bootsrap & log via openhab community
See row 2557
2023-12-05 11:28:23.601 [DEBUG] [rnal.model.UniFiProtectCameraChannel] - Failed to load channel: is-ringing

**Comment by seaside1** [comment] 2023-12-06 07:28
Thanks I'll try to take a look. Funny thing is that i can't reproduce this with my doorbell now, it always seem to work.

**Comment by seaside1** [comment] 2023-12-18 18:39
Hi!
So I have looked at the logs and also done tests on my system. The logs seem to miss the doorbell events, so either it is not connected or there is some glitch in the websocket api.
When this happens, does the doorbell work? I mean can you see in the UniFiProtect app that you have a ring-event?
For me it seems to work now, and it is more stable.

**Comment by SchmidSP** [comment] 2023-12-18 18:47
Hi. Yes App and Homebridge Unifiy Protect Connector (for Homekit) receive the ring Signal. When I restart the Openhab binding I receive one or two time a ring. After that it stop working. Did you need further logs? I'm now for testing on 2.10.11. Thanks.

**Comment by SchmidSP** [comment] 2023-12-18 18:52
Addition: I also see the in the Openhab log a few times after ring the last ring:
Ring was a few seconds before then
A few seconds later:
2023-12-18 19:51:14.330 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'G4DBLastRing' changed from 2023-12-18T17:24:45.423+0100 to 2023-12-18T19:50:42.406+0100

**Comment by SchmidSP** [comment] 2023-12-18 18:57
restart unify nvr thing, ring works again:

2023-12-18 19:54:46.240 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'unifiprotect:nvr:96ec58672e' changed from INITIALIZING to ONLINE
2023-12-18 19:54:46.254 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'unifiprotect:g4doorbell:9c94e07c1d' changed from UNINITIALIZED (BRIDGE_UNINITIALIZED) to INITIALIZING
2023-12-18 19:54:46.264 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'unifiprotect:g4doorbell:9c94e07c1d' changed from INITIALIZING to ONLINE
2023-12-18 19:54:46.377 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'CKG2PNvrUptime' changed from 1723832400 to 1723862400
2023-12-18 19:54:46.383 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'CKG2PNvrLastSeen' changed from 2023-12-18T19:54:09.392+0100 to 2023-12-18T19:54:39.393+0100
2023-12-18 19:54:46.399 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'CKG2PNvrCpuLoad' changed from 13.600000000000001 to 7.8
2023-12-18 19:54:46.419 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'CKG2PNvrMemAvailable' changed from 598072 to 598148
2023-12-18 19:54:46.423 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'CKG2PNvrMemTotal' changed from 170316 to 177688
2023-12-18 19:54:46.435 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'G4DBLastSeen' changed from 2023-12-18T19:53:20.054+0100 to 2023-12-18T19:54:25.058+0100

2023-12-18 19:55:05.371 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'G4DBIsRinging' changed from ON to OFF

Stop working after a few hours again...

**Comment by seaside1** [comment] 2023-12-18 18:57
When it stops working, does motion detection still work?

**Comment by SchmidSP** [comment] 2023-12-18 19:27
I have to check. Must wait till the error start again.

**Comment by SchmidSP** [comment] 2023-12-19 07:49
Checked. Also no Motion. See event.log and openhab.log attached.
[events.log](https://github.com/seaside1/unifiprotect/files/13712599/events.log)
[openhab.log](https://github.com/seaside1/unifiprotect/files/13712600/openhab.log)

**Comment by SchmidSP** [comment] 2023-12-20 15:00
More Logs (with debug enabled) to help.
[openhab.log](https://github.com/seaside1/unifiprotect/files/13728815/openhab.log)

Successful Ring after restart working: 2023-12-20 14:21:13.033

Failed Ring 1 hour later no signal: 2023-12-20 15:23:13.xxx

**Comment by SchmidSP** [comment] 2023-12-20 15:02
Password changed ;) after debug.

**Comment by Magicsplash** [comment] 2023-12-29 23:05
Have you managed to get any progress with this one? 

I'm experiencing a similar problem where the 'is-ringing', motion-detection etc. all stop responding. 
The 'last-ring' and 'last-seen' will still, strangely enough, work.

Could it be the NVR websocket disconnecting due to a time-out to be the main culprit?

Cheers.

To add, only a reboot of the openhab service fixes things.

**Comment by SchmidSP** [comment] 2024-01-09 18:29
Hi, any news or could I assist with more Information?

**Comment by seaside1** [comment] 2024-01-26 12:56
So I have not managed to work that much on it.
Some short notes:
- The websocket fails silently for these types of events, it does get messages like updates of disk usage etc so it's not completely dead but not taking motion events or ring events
- The watchdog in the binding is not working at all
- Installing the latest uniFi Protect (2.11.19 or 2.11.21) seems to reduce the problem. My system works for up to a week and then starts failing.
- Restarting the binding seems to fix the issue (as a workaround)

Since I also experience this problem I will continue to look into getting a solution up and running.
Possibly using more than one single websocket could be a solution as long as they are shut down properly .

**Comment by SchmidSP** [comment] 2024-01-26 13:11
Hi, maybe it helps.
I also use unifyprotect homebridge plugin (https://github.com/hjdhjd/homebridge-unifi-protect).
The homebridge plugin works very stable with websocket connection.
Maybe you find something that help you.
Another Idea, disconnect and restart the websocket connection every 10 min could solve the problem until we know what the trigger is.
I will test the new unifi build and give you feedback.

**Comment by seaside1** [comment] 2024-01-26 14:02
Yes I know about both homebridge and homeassistant solution since start of this project.
I like you suggestion, you can try https://github.com/seaside1/unifiprotect/releases/tag/unifiprotect-4.0.0-v1.3
Which will restart the binding each 10 mins if the force watch dog option in NVR is set to true (default).

This would just be a temporary solution until I can find the root cause.

**Comment by SchmidSP** [comment] 2024-01-26 14:48
Hi,

thanks. Test with 4.0.0-v1.3 started.

**Comment by SchmidSP** [comment] 2024-01-31 15:48
Unfortunately bad news. 
Even with the Watchdog 10 minute restart on (hook watchdog is on), "ringing" stops working after a few Minutes.
Any ideas?

**Comment by seaside1** [comment] 2024-01-31 21:40
I have experienced this myself as well. Although it takes around 4-7 days for me to get failure.
The reinit is not working, so I have refactored it. I'll try a bit locally if it seems to work I will release a pre-release of it.

**Comment by seaside1** [comment] 2024-02-07 20:22
That last build was a mess. I'm leaning towards that this issue occurs when your token is no longer valid. The normal NVR flows, like getting snapshots etc, will login again creating a new token. When this happens the websocket should probably be reinitialized.  I have written some code that does this. My second approach would be to use another httpClient just for the websocket, but use the same token and cookies.

If my first approach does not work, I will try the second. This is somewhat slow to test, like I said my system is usually fine for at least a couple of days before the socket stops working.

**Comment by SchmidSP** [comment] 2024-02-07 20:40
Hi, maybe I can help you.
Just let me know what you need for support. I can do testing and debugging for you if you want.

**Comment by seaside1** [comment] 2024-02-12 18:59
Rework the websocket, maybe you can test? This seems a lot more stable in my system. The watchdog is removed though.
https://github.com/seaside1/unifiprotect/releases/tag/unifiprotect-4.0.0-v1.3

**Comment by SchmidSP** [comment] 2024-02-13 08:53
Installed. Give you feedback in a few days.

**Comment by SchmidSP** [comment] 2024-02-15 10:05
Feedback: Works now since 2 days. Websocket stable. Ring signal working. Can't see any errors in logs.
Thanks a lot for this great work!

**Comment by marioschouten** [comment] 2024-02-16 01:43
Been running v13 since it was released, don't have a G4 camera but it solved my other issues and just wanted to say thank you very much for the great work. Very much appriciated.

**Comment by seaside1** [comment] 2024-02-16 10:32
Thanks for the feedback. Closing this one for now.

**Closed as completed by seaside1** 2024-02-16 10:32 UTC
